### ISSUE TITLE
Send fees to treasury using IDA not ERC20 transfers

### ISSUE THREAD

**Issue by mikeghen** [mikeghen/rickoshea#32]
Right now the fees for services are sent to the DAO treasury using ERC20 transfers. Thi issue involves converting them to use the IDAs setup to distribute tokens to streamers. This will remove ERC20 transfers from the mix and make things more gas efficient.

**Comment by vaibhavgeek** [comment]
@mikeghen I intend to pick up this issue (have experience with superfluid / solidity), is there a way I can reach out to you for clarifications and more information?

**Comment by rashtrakoff** [comment]
> @mikeghen I intend to pick up this issue (have experience with superfluid / solidity), is there a way I can reach out to you for clarifications and more information?

Did you find your way to our Discord server ? If not, here is the invite: https://discord.gg/HNbZyh63 (Link expires in seven days).
